config/routes.rb
Rails.application.routes.draw do

  	devise_for :users
	resources :tasks do 
		member do 
			patch :complete
		end
	end
	root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
end

app/models/task.rb
class Task < ApplicationRecord

	belongs_to :user
	

	def completed? 
		!completed_at.blank?
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tasks, dependent: :destroy#can use :dependent => delete_all(callbacks will not be executed) or destroy (more preferred)
	#e.g. dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable




  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_action :find_task, only: [:show, :edit, :update, :destroy]
	#can use this in application controller to allow for it to persist in all pages.

	def index 
		if user_signed_in?
			if params[:category].blank?
				# @tasks = Task.where(:user_id => current_user.id).order("created_at DESC")
				@tasks = current_user.tasks.order("created_at DESC")
			else 
				@category = Category.find_by(name: params[:category])
				@tasks = @category.tasks.where(user: current_user).order("created_at DESC")
			end


			# @pending_task = Task.where("duedate BETWEEN ? AND ?", Date.today, Date.today.advance(:days => +7))
			# @overdue_task = Task.where("duedate < ?", Date.today)
			#learnt from vincet. Potentially add-on. 

		end
	end

	def show 
	end

	def new 
		@task = current_user.tasks.new
	end

	def create
		@task = current_user.tasks.new(task_params)   
		
		if @task.save 
			flash[:notice] = "Task successfully created."
			redirect_to root_path
		else
			flash[:error] = "Task not created, please try again."
			render 'new'
		end
	end

	def edit
	end

	def update 
		if @task.update(task_params)
			flash[:notice] = "Task successfully updated."
			redirect_to task_path(@task) 
		else 
			flash[:error] = "Task not updated, please try again."
			render 'edit'
		end
	end

	def destroy 
		@task.destroy
		flash[:notice] = "Task successfully destroyed."
		redirect_to root_path
	end

	def complete 
		@task = Task.find(params[:id])
		@task.update_attributes(:completed_at => Time.now)
		flash[:notice] = "Task completed. Well done!"
		redirect_to root_path 
	end

	private
	def task_params 
		params.require(:task).permit(:title, :description, :duedate, :priority)
	end

	def find_task
		@task = Task.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListApp</title>
    <%= csrf_meta_tags %>
    <script src="https://use.fontawesome.com/f18f65954f.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  
    <link href="https://fonts.googleapis.com/css?family=Caveat|Dancing+Script|Dosis|Encode+Sans+Condensed|Lato|Libre+Barcode+39+Text|Lobster|Roboto|Zilla+Slab+Highlight" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	  <nav class="navbar navbar-inverse bg-inverse">
	  	<div class="container">
	  		<div class="navbar-header">
	  			<%= link_to "TASK LIST", root_path, class: "navbar-brand" %>
	  		</div>
	  		<ul class="nav navbar-nav navbar-right">
	  			<% if current_user.present? %>
	  				<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
	  			<%	else %> 
	  				<li><%= link_to "Log In", new_user_session_path %></li>
	  				<li><%= link_to "Sign Up", new_user_registration_path %></li>
	  			<% end %>
	  		</ul>
	  		<% if user_signed_in? %>
	  			<%= link_to "Create Task", new_task_path, class: "navbar-text navbar-link" %>
	  			

			
			<% Category.all.each do |category| %>
				
				<%= link_to category.name, tasks_path(category: category.name), class: "navbar-text navbar-link" %> 

			<% end %>
	
	  			
	  		<% end %>
	  </nav>
	  	</div>

	  

<div class="container">

		<% if flash[:notice] %>
		  <div class="alert alert-success">
		    <%= flash[:notice] %>
		  </div>
		<% end %>

		<% if flash[:error] %>
		  <div class="alert alert-danger">
		    <%= flash[:error] %>
		  </div>
		<% end %>

<!-- for a generic color display for alert, use the below --> 
	<!-- <div>
      <% flash.each do |key, value| %>
        <% if key == [:notice] %>
        <div class="alert alert-success" role="alert"> <%= value %> </div>
        <% else %>
        <div class="alert alert-danger" role="alert"> <%= value %> </div>
      <% end %>
      <% end %>
    </div> -->





	<%= yield %>


</div>
    
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>

  <%= f.input :title, label:"Task" %>
  <%= f.input :description %>
  <%= f.input :duedate %>
<!--   <%= f.input :priority, label:"Priority (1 - High, 2 - Medium, 3 - Low)"%> -->
<%= f.select :priority, [['High', 1], ['Medium', 2], ['Low', 3]], {prompt: "Rank Priority" }%> <br> <br>
  

  <br>
  <br>

  <%= f.button :submit %>
<% end %>

app/views/tasks/_welcome_page.html.erb
<div class="row">
<div class="col-md-10 col-md-offset-1 welcome">

	<br>
	<h1 class="welcome">Sherlynn's<br> To-Do List Application</h1>
		<br>
	<h3>Online Task Management Application</h3>
		<br> 
		<br>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger btn-lg" %>
</div> 
</div>

app/views/tasks/edit.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>Edit To-Do Item</h1>

	<%= render 'form' %>

</div>

app/views/tasks/index.html.erb
<% if user_signed_in? %>
<!-- checks to see if a user is signed in, otherwise, it will render a landing page asking the user to login or sign up --> 

<div class="col-md-10 col-md-offset-1">
	<% @tasks.each do |task| %> 
		<div class="index-wrapper">
			
			<% if task.completed? %> 
<!-- START FOR COMPLETED ITEMS --> 
			
			<div class="row task">
				<!-- FOR TICK ICON --> 
				<div class="col-md-2">
					<p><%=link_to complete_task_path(task), method: :patch do %></p> 
						<i class="fa fa-check fa-lg" aria-hidden="true"></i>
						<% end %>
				</div>

				<!-- FOR TRASH ICON --> 
				<div class="col-md-2">
					<p><%= link_to task, method: :delete, data: { confirm: "Are you sure?" } do %> </p>
						<i class="fa fa-trash fa-lg"></i>
						<% end %>
				</div>

				<!-- FOR TASK --> 
				<div class="col-md-8">
					<h2 style="opacity: 0.5;" class="task-title"><strike><%= link_to task.title, task %> </strike></h2>
					<p style="opacity: 0.5;" class="task-sub-title task-desc">Description: <%= task.description %></p>
					<p style="opacity: 0.5;" class="task-sub-title task-desc">Due-date: <%= task.duedate.strftime("%d %b %Y %A") %></p>

					<p style="opacity: 0.5;" class="task-sub-title task-desc"> 
							<% if task.priority == 1  %>
								<p>Priority: High</p>
							<% elsif  task.priority  == 2 %>
								<p>Priority: Medium</p>
							<% else %>
								<p>Priority: Low</p>
							<% end %> 
						</p>
					<p style="opacity: 0.5:" class="time-created-at task-sub-title">Completed <%= time_ago_in_words(task.completed_at) %> ago</p>




				</div>
			</div>
<!-- END FOR COMPLETED ITEMS --> 
			<% else %> 
<!-- START of NOT COMPLETED ITEMS --> 	
				<div class="row task">
					<div class="col-md-2">
						<p><%= link_to complete_task_path(task), method: :patch do %></p>
							<i class="fa fa-check fa-lg"></i>
							<% end %>
					</div>

					<div class="col-md-8">
						<h2 class="task-title"><%= link_to task.title, task%></h2>
						<p class="task-sub-title task-desc">Description: <%= task.description %></p>
						<p class="task-sub-title task-desc">Due-date: <%= task.duedate.strftime("%d %b %Y %A") %></p>
						<p class="task-sub-title task-desc"> 
							<% if task.priority == 1  %>
								<p>Priority: High</p>
							<% elsif  task.priority  == 2 %>
								<p>Priority: Medium</p>
							<% else %>
								<p>Priority: Low</p>
							<% end %> 
						</p>

						<p style="opacity: 0.5;" class="time-created-at task-sub-title">Created <%= time_ago_in_words(task.created_at) %> ago</p>
					</div>

					<div class="col-md-2">
						<p><%= link_to task, method: :delete, data: {confirm: "Are you sure?"} do %></p>
							<i class="fa fa-trash fa-lg"></i>
							<% end %>
					</div>

				</div>

<!-- END of NOT COMPLETED ITEMS --> 		
			<% end %> <!-- END THE IF-ELSE --> 
		</div>


	<% end %> <!-- END THE EACH-DO --> 
</div>
	



<% else %>

	<%= render 'welcome_page' %>

<% end %> 

app/views/tasks/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>New To-Do Item</h1>

	<%= render 'form' %>

</div>

app/views/tasks/show.html.erb
<div class="col-md-10 col-md-offset-1">
<div class="table-responsive">
  <table class="table table table-hover">

	<h1><%= @task.title %></h1>


	    <thead>
	      <tr>
	        <th>Task Description</th>
	        <th>Created Date</th>
	        <th>Due</th>
	        <th>Priority</th>
	        <th>Category</th>
	      </tr>
	    </thead>
	    <tbody>
	      <tr>
	        <td><%= @task.description %></td>
	        <td><%= @task.created_at.strftime("%d %b %Y %A, %I:%S %p") %></td>
	        <td><%= @task.duedate.strftime("%d %b %Y %A") %></td>
	        <td> 
			<% if @task.priority == 1  %>
				<p>High</p>
			<% elsif  @task.priority  == 2 %>
				<p>Medium</p>
			<% else %>
				<p>Low</p>
			<% end %>
	        </td>
	        <td>
		        <% if @task.category_id == 1  %>
					<p>Work</p>
				<% elsif  @task.category_id  == 2 %>
					<p>Groceries</p>
				<% elsif  @task.category_id  == 3 %>
					<p>Family</p>
				<% elsif  @task.category_id  == 4 %>
					<p>Hobby</p>
				<% elsif  @task.category_id  == 5 %>
					<p>Friends</p>
				<% else %>
					<p>Others</p>
				<% end %>
	        </td>
	        <br>
	      </tr>
	    </tbody>
	  </table>
	</div>





<!-- <img src="<%= asset_path 'icandoit' %>" > -->



	<div class="col-md-4 col-md-offset-4">
	<button type="button" class="btn btn-warning btn-lg">
		<%= link_to "Back", root_path %>
	</button>

	<button type="button" class="btn btn-warning btn-lg">
		<%= link_to "Edit", edit_task_path(@task) %> 
	</button>

	<button type="button" class="btn btn-warning btn-lg">
		<%= link_to "Delete", task_path(@task), 
			method: :delete, 
			data: {confirm: "Are you sure you want to delete this task?"} %> 
	</button>
	<br>


	</div>
	

  </table>
</div>

</div>